spring:
  application:
    name: midia_be
  data:
    redis:
      client-name: midia-be
      host: ${REDIS_HOST:localhost}
      port: 6379
      database: 0
      timeout: 10s

springdoc:
  show-actuator: true
  version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"

cors:
  allowed-origins:
    - http://localhost:5173

dgs:
  graphql:
    virtualthreads:
      enabled: true
    schema-locations: classpath*:graphql-client/*.graphql*
    extensions:
      validation:
        enabled: true
      scalars:
        enabled: true

jwt:
  signer-key: "3ac67e1f13d6744c9e5158c0508a91da54696589d871c20750f16a24838c49322096f9e541173311b2f11c94bc11734d157b7174bb78b0e2a57d3a2dd4f40ef0"
  valid-duration: 60 # in seconds
  refresh-duration: 3600 # in seconds

server:
  port: 8000 # for avoid port conflict with dgraph standalone container which run in port 8080

dgraph:
  address: ${DGRAPH_ADDRESS:localhost}
  port: ${DGRAPH_PORT:9080}